image: node:18

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm

stages:
  - build
  - lint
  - test
  - deploy

before_script:
  - rm -rf node_modules
  - npm ci

build:
  stage: build
  script:
    - npm run build
  tags:
    - aws-frontend

lint:
  stage: lint
  script:
    - npm run lint
  tags:
    - aws-frontend

unit-test:
  stage: test
  script:
    - npm run test
  tags:
    - aws-frontend

deploy:
  stage: deploy
  script:
    - git config --global user.name "$GITHUB_USERNAME"
    - git config --global user.email "$GIT_EMAIL"
    - git clone --mirror https://$GITHUB_TOKEN@github.com/$GITHUB_REPO.git $APP_NAME
    - cd $APP_NAME
    - git push --mirror https://$GITHUB_TOKEN@github.com/$GITHUB_REPO.git
  tags:
    - aws-frontend
  only:
    - main
