stages:
  - build
  - lint
  - test

build-job:
  stage: build
  script:
    - npm install
    - npm run build

lint-test-job:
  stage: lint
  script:
    - npm run lint

unit-test-job:
  stage: test
  script:
    - npm run test
