image: node:18-alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - build
  - lint
  - test

before_script:
  - npm ci

build:
  stage: build
  script:
    - npm run build

lint:
  stage: lint
  script:
    - npm run lint

unit-test:
  stage: test
  script:
    - npm run test
