image: node:18-alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm

stages:
  - build
  - lint
  - test

before_script:
  - rm -rf node_modules
  - npm ci

build:
  stage: build
  script:
    - npm run build
  tags:
    - aws-frontend

lint:
  stage: lint
  script:
    - npm run lint
  tags:
    - aws-frontend

unit-test:
  stage: test
  script:
    - npm run test
  tags:
    - aws-frontend
