version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: dashboard-ezenplo
    working_dir: /app
    environment:
      NODE_ENV: production
