#!/bin/sh
current_branch=$(git symbolic-ref --short HEAD)

if echo "$current_branch" | grep -E -q '^(feature|fix)/US-[0-9]{3,}' || echo "$current_branch" | grep -E -q '^(feature|fix)/NOUS'; then
    echo "Branch name follows the required format: 'feature/US-XXX-description' or 'fix/US-XXX-description' or 'feature/NOUS' or 'fix/NOUS' - Push successful"
    exit 0
else
    echo "Error - Branch name does not follow the required format: 'feature/US-XXX-description' or 'fix/US-XXX-description' or 'feature/NOUS' or 'fix/NOUS'"
    exit 1
fi